### ISSUE TITLE
iOS - getting developerPayload

### ISSUE THREAD

**Issue by erjdriver** [PeterStaev/nativescript-purchase#10]
Seems like on iOS platform, one cannot pass the developerPayload to buyProduct() method.

Any suggestions how this could be done on iOS?

Incidentally even though plugin doesn support subscription so far- on iOS it seems to be working as long as I can get this to work (though it's more app specific). At least I'm getting the prompt to purchase and getting a purchase notification.

Thanks.

p.s. this is really not a plug-in issue but didn't know of another way to contact you.

**Comment by PeterStaev** [comment]
Hey @erjdriver , Apple does not have a developer payload option to be sent when making purchases. That's why the plugin does not currently support it. From I see this can be added, so flagging this as enhancement and will see to add it in one of the future versions. Thanks!

**Comment by erjdriver** [comment]
Thank you.

Yes I could store the payload in the app itself - user will not be initiating concurrent purchases anyway.

As I wrote above, not sure what's working or not working - but on iOS - auto-renewing subscriptions seem to work. Maybe nothing is happening on itunesconnect - but I see a full purchase process.

On Android, in-app purchases are are working - not subscriptions.

Thanks.

**Comment by erjdriver** [comment]
Haven't tested it - but thank you.

Is there a patreon page or a PP account?

**Comment by PeterStaev** [comment]
@erjdriver you can use the company's PP donation page: https://bit.ly/2AS9QKB
