### ISSUE TITLE
How to get refunded products?

### ISSUE THREAD

**Issue by dacalleg** [PeterStaev/nativescript-purchase#104]
There seems to be no way to get the list of products that have been reimbursed. How can you get it?

**Comment by PeterStaev** [comment]
Hey @dacalleg , 

I haven't personally handled refunds, but from what I see for Apple people recommend to call restore purchases, which should not have the refunded product. 

For android you should get a `Refunded` state transaction at some point. 

Hope this helps.

**Comment by dacalleg** [comment]
I have made a purchase, refund It using oreder management in Play Store and call restorePurchase() method(after One day). It returned an object that contains original tranaction: purchased and transaction: restored. I see that in the code the transaction: restored Is hardcoded.

**Comment by PeterStaev** [comment]
From what I see from other users the Android refunds can take up to 3 days to be reflected: https://stackoverflow.com/questions/13861625/in-app-billing-v3-dont-detect-refund

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
