### ISSUE TITLE
Consume Purchase Documentation

### ISSUE THREAD

**Issue by NicholasSmilovic** [PeterStaev/nativescript-purchase#109]
https://npm.proplugins.org/-/web/detail/@proplugins/nativescript-purchase says:
![image](https://user-images.githubusercontent.com/29617334/112332739-61dd3b80-8c90-11eb-8601-3097feae0c03.png)

but looking at the source code the promise isn't returning the `billingResult.getResponseCode()`
```
export function consumePurchase(token) {
    return new Promise((resolve, reject) => {
****
                if (billingResult.getResponseCode() === ***) {
                    resolve();
                }
****
    });
}

```

Using stars to hide the proplugin code in case it shouldn't be shared

**Comment by PeterStaev** [comment]
Hey @NicholasSmilovic , seems the readme was not adjusted when I migrated the plugin from AIDL to the Google Play Billing lib. The promise no longer returns int value. Instead if it is successful the promise is resolved, if there is a problem the promise will be rejected. I've adjusted the readme in the ProPlugins Git:
![image](https://user-images.githubusercontent.com/9464097/112867943-285b6480-90c4-11eb-9bcd-092e9232778e.png)
