### ISSUE TITLE
Get the current user's active subscriptions

### ISSUE THREAD

**Issue by tangerinegit** [PeterStaev/nativescript-purchase#112]
Hello,

Is there a way to see the current user's active subscriptions on Android?  I thought getStoreReceipt() would work, but according to the documentation, on Android this always comes back as undefined.

Thank you.

**Comment by PeterStaev** [comment]
@tangerinegit I haven't implemented subscriptions, but I think for android you need the `transactionReceipt`  that is in the transaction when you bought the subscription. At least this is how I read the docs:
![image](https://user-images.githubusercontent.com/9464097/118883528-04671300-b8fe-11eb-932e-e8afa29bb7e5.png)
The plugin populates the token into the `transactionReceipt` property.
