### ISSUE TITLE
Question - how to clear stored apple id / password

### ISSUE THREAD

**Issue by jgmedialtd** [PeterStaev/nativescript-purchase#115]
When you fire the init() method, the user is prompted for an apple id and password. 

- They aren't prompted for this more than once. Where is information stored, and can it be cleared? I have attempted logging out of the device but this doesn't do the trick
- Is there any way to default to the currently signed in apple id rather than requiring this information to be typed in again?

Many thanks

**Comment by PeterStaev** [comment]
Hey @jgmediadesign , you are probably testing in simulator/sandbox environment. From what I know the StoreKit (and this plugin itself) should reuse the account that the user used in the App Store.

**Comment by jgmedialtd** [comment]
OK thanks @PeterStaev - you're right - we're only testing in TestFlight at the moment which uses the sandbox account.

**Comment by PeterStaev** [comment]
@jgmediadesign , sadly I'm not sure if there is any way of resetting the saved credential. Try removing the app and reinstalling it.
