### ISSUE TITLE
Consuming Android Purchase after error (getPurchases)

### ISSUE THREAD

**Issue by Roar1827** [PeterStaev/nativescript-purchase#13]
I am trying to consume a purchase that failed to consume, and I now don't know the receipt for.

Is there a way to call [getPurchases](https://github.com/PeterStaev/nativescript-purchase/blob/dcea929bece264664bfe5cc2a528bf79763a4a05/android/inappbilling/inappbillinghelper/src/main/aidl/com/android/vending/billing/IInAppBillingService.aidl#L132) and use this info to then consume the product?

**Comment by PeterStaev** [comment]
Hey @Roar1827 , I think you should be able to do that by calling the [restorePurchases](https://github.com/PeterStaev/nativescript-purchase/blob/master/purchase.android.ts#L98) method. This should trigger the transaction updated even where you will have the original transaction.
