### ISSUE TITLE
Where is the transaction date?

### ISSUE THREAD

**Issue by oncul** [PeterStaev/nativescript-purchase#16]
Hello i need transaction date for purchased products. When i call restorePurchases its gettin just this

```
JS: {
JS:     "nativeValue": null,
JS:     "originalTransaction": {
JS:         "nativeValue": {
JS:             "constructor": "constructor()function () { [native code] }"
JS:         },
JS:         "transactionState": "purchased",
JS:         "productIdentifier": "android.test.purchased",
JS:         "transactionReceipt": "inapp:com.ttt.mmm.test.purchased",
JS:         "dataSignature": "",
JS:         "transactionIdentifier": "transactionId.android.test.purchased",
JS:         "developerPayload": ""
JS:     },
JS:     "transactionState": "restored"
JS: }
```

**Comment by PeterStaev** [comment]
Hey @cagatayoncul , if the `purcahseTime` is returned from the Google Play services then a `transactionDate` field will be available in the transaction object. I can only assume that in your case for some reason the the `purchaseTime` is 0. You can explore the `nativeValue` object which is a Java `JSONObject` and see what properties Google is returning. 

Note that when you are testing with sandbox purchases for some fields Google does not return a valid value (for example `orderId`).
