### ISSUE TITLE
Consume purchase problem!

### ISSUE THREAD

**Issue by oncul** [PeterStaev/nativescript-purchase#17]
I am trying to consume purchase but i am getting this error

Error: java.lang.Exception: Product already purchased. Where is the problem i am testing on real device and using fake ids.

```
purchase.init([
    "android.test.purchased"
]);
```

```
purchase.on(purchase.transactionUpdatedEvent, function(transaction){
        console.dir(transaction);

        if (transaction.transactionState === TransactionState.Purchased && transaction.productIdentifier.indexOf(".purchased") >= 0) {
            purchase.consumePurchase(transaction.transactionReceipt)
                .then(function(responseCode) { console.log(responseCode) }) // If responseCode === 0 the purchase has been successfully consumed
                .catch(function(e) { console.log(e) });
        }
    });
```

**Comment by PeterStaev** [comment]
Hey @cagatayoncul , like the error says the problem is not with the consumption, but you are trying to purchase a product that is already purchased. Note that even with android test purchases you can only buy them once unless you consume them.

**Comment by oncul** [comment]
ok i solved this. need to add consumepurchase() func after buyproduct() like this

```
purchase.consumePurchase(transaction.transactionReceipt)
                .then(function(responseCode) {
                    _consume = true;

                }) // If responseCode === 0 the purchase has been successfully consumed
                .catch(function(e) { console.log(e); console.log('hata'); });
```

**Comment by RoyiNamir** [comment]
@PeterStaev  @cagatayoncul  How can I catch this "already purchased" error ?
It is thrown at global level.

![image](https://user-images.githubusercontent.com/2842123/41466751-3e488e8e-70ac-11e8-80e2-a134d3baef62.png)

**Comment by mid787** [comment]
@PeterStaev  @cagatayoncul  How can I catch this "already purchased" error ?
It is thrown at global level.

![image](https://user-images.githubusercontent.com/2842123/41466751-3e488e8e-70ac-11e8-80e2-a134d3baef62.png)

**Comment by outsideMyBox** [comment]
I also ran into the 'Product already purchased!' exception when a user tries to purchase a product already purchased. It's a bit annoying as the behaviour is different for each platform (on iOS there is no exception and the system restores the purchase after displaying dialogs). My workaround/hack is to add a try block:

```
try {
   purchase.buyProduct(product)
}
catch (err) {
     if (err.message.startsWith('java.lang.Exception: Product already purchased!')) {
        // some warning messages...
       purchase.restorePurchases();
      }
     else {
       //  ...
     }
}
```
