### ISSUE TITLE
iOS - purchase notification not happening on iOS 11

### ISSUE THREAD

**Issue by erjdriver** [PeterStaev/nativescript-purchase#23]
Purchase notifications are not happening on iOS 11.

Thanks.

**Comment by PeterStaev** [comment]
Hey @erjdriver , just to confirm if you deploy the same application on iOS10 device your workflow is working and on iOS11 it does not? Or are you testing on iOS11 only?

**Comment by erjdriver** [comment]
Disregard - installed ios 11 and it works.

But I've had some customers go thru the workflow and the app is not getting the callback on successful purchase.
