### ISSUE TITLE
Android not purchasing

### ISSUE THREAD

**Issue by rafaelcmrj** [PeterStaev/nativescript-purchase#24]
I'm trying to implement in-app purchase in an Android app but it isn't working. It worked at the first time but now it only returns "Purchasing" status (instead of "Purchased".

**Comment by PeterStaev** [comment]
Hey @rafaelcmrj , with this less info I'm not sure I can help you much. When did it stop working? What changes have you made before it stopped? It is best you work with your code and see what you did around the time when it stopped working so we can isolate the problem.

**Comment by rafaelcmrj** [comment]
@PeterStaev that's the problem, I did not change the code. What happened was that I could purchase in the first time, but I didn't consume the product, so now I can't buy and (and can't consume if I can't buy)... how to proceed?

**Comment by PeterStaev** [comment]
@rafaelcmrj , if you did not consume the purchase then you cannot buy it again. You will have to set up a new product id to test your new workflow that includes a consume. Or you should test from a different store login. 

I would recommend during testing for you to always combine buy with consume as it is easier to just remove the consume than to experience the problems you have now with a bought but unconsumed product.

**Comment by rafaelcmrj** [comment]
I will try creating a new one though... I did have a consume() code, but only after I bought it I figured out that the example .indexOf('.consume') is related to my product name.
