### ISSUE TITLE
Get the ORDER-ID field

### ISSUE THREAD

**Issue by erjdriver** [PeterStaev/nativescript-purchase#27]
On a purchase notification, right now I get access to a "trans_receipt" field which doesn't seem to correlate to anything the customer sees or receives.

But in the Apple iTunes receipt - they do get an ORDER-ID field - would it be possible to get that field?

**Comment by PeterStaev** [comment]
Hey @erjdriver , there is no such property. You can see all the available properties on iOS [here](https://developer.apple.com/documentation/storekit/skpaymenttransaction). You can check what you receive in the `transactionIdentifier` field, but not sure if that is going to be the same as the Order ID.
