### ISSUE TITLE
In app subscriptions

### ISSUE THREAD

**Issue by westlakem** [PeterStaev/nativescript-purchase#30]
In the step-by-step documents, you say that the plugin does not support subscription products, yet the readme shows the "subscription period" as one of the product variables.  Does this plugin support subs?

**Comment by PeterStaev** [comment]
The article says "for now" ;) As of version 2.0.0 the plugin supports subscriptions.

**Comment by westlakem** [comment]
@PeterStaev That is awesome!  Any chance you can update the in-depth tutorials to show that?

**Comment by PeterStaev** [comment]
There will be a separate article about subscriptions. The tutorials are still valid for both in-app purchase and subscriptions.

**Comment by PhilippS93** [comment]
@PeterStaev , is the tutorial already out there? Thank you!

**Comment by PeterStaev** [comment]
No tutorial yet. And dont think there will be - there are already lots of articles how to validate subscriptions on both platforms. And those wont differ much from the NS way. Since all the backend code that will reside on your server will be the same as in the native tutorials.
