### ISSUE TITLE
Check Subscription Status

### ISSUE THREAD

**Issue by westlakem** [PeterStaev/nativescript-purchase#31]
Is there a way from within the app to see if the subscription is active or the product is purchased?  EX: (using angular)

XML:
```
<StackLayout [visibility]="isSubscriber()">
...
</StackLayout>
```
Component.ts:
```
isSubscriber() {
  purchase.hasProduct(product)
}
```
OR
```
isSubscriber(){
  purchase.hasCurrentSubscription(product)
end
```
OR (probably preferred)
```
let validSubscriptions = [product1, product2, product3]
isSubscriber(){
  purchase.hasAnySubscription(validSubscriptions)
}
```

**Comment by PeterStaev** [comment]
Hey @westlakem , the check for subscription validity should be performed by your backend. The plugin does not do any kind of verification. So what you need to do is call your backend and do the verification there, 

For android you can check here:
https://developer.android.com/google/play/billing/billing_subscriptions.html#realtime-notifications
https://developer.android.com/google/play/billing/billing_subscriptions.html#strategies

For iOS:
https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html#//apple_ref/doc/uid/TP40010573-CH104-SW1

I have a blog article in the works that would explain this, but I haven't got the time recently to complete it...

**Comment by westlakem** [comment]
@PeterStaev My app doesn't have a back end to it.  I just want to be able to show some fields when someone is a subscriber, and some others when they are not.

**Comment by PeterStaev** [comment]
In this case you will have to write native code in your app in order to validate your subscriptions. Since all nativescript apps are basically free text it is not recommended to write the validation steps in your app, because all the info (including the iTunes shared secret needed) could easily be read. That's why the plugin will support out of the box only server-to-server validation.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
