### ISSUE TITLE
Billing permission

### ISSUE THREAD

**Issue by r0zar** [PeterStaev/nativescript-purchase#32]
Does installing the plug in automatically set up the billing permission via the helper? 
Thanks.

**Comment by PeterStaev** [comment]
Hey @r0zar , not sure what helper you mean, but no the plugin does not set up the entitlements automatically. Please refer to the step by step guides in the readme.

**Comment by r0zar** [comment]
I was reviewing the guides last night but I didn't see any mention of
adding the com.android.vendor.BILLING permission anywhere.
I found mention of the line of code in the plugin src code and wondered if
it is configured via the plugin

**Comment by r0zar** [comment]
File in question: https://github.com/PeterStaev/nativescript-purchase/blob/master/android/inappbilling/inappbillinghelper/src/main/AndroidManifest.xml

**Comment by PeterStaev** [comment]
Aha, yes, you mean the android permissions. I thought you mean for iOS. 

Yes for Android the permissions will be added automatically.

**Comment by r0zar** [comment]
Thank you! Makes sense
