### ISSUE TITLE
Getting empty array from purchase.getProducts

### ISSUE THREAD

**Issue by BearOutThere** [PeterStaev/nativescript-purchase#33]
I've followed the guide step by step.  The application apk is published to alpha and i can install it both on the emulator with PlayStore and on the android device using test accounts.  The products are loaded, are active, and available in all countries.  But when i run the app both on the device and in the emulator no products are shown.  When i debug the application in the emulator the purchase.getProducts().then callback is called but the response array is empty.  I'm stumped.
Any help or suggestions would be greatly appreciated.
Thanks in advance.

**Comment by BearOutThere** [comment]
Figured it out on my own.  The test user i added for emulator testing was not included in the list of license testers.   After that was fixed the array came back with all the products.  
FYI:  using an emulator version with the Play Store works for local development and debugging.  No need to upload every change up to the Google Play.

**Comment by PeterStaev** [comment]
Hey @bearoutthere , at the time of the writings there was no official Google Play Store image for the stock android emulator 😄 So good to know it works with that one! Thanks!

**Comment by BearOutThere** [comment]
Just got it working with the test purchase.  Everything works just fine.  Thanks for a great component.
