### ISSUE TITLE
Subscription API (ios)

### ISSUE THREAD

**Issue by erjdriver** [PeterStaev/nativescript-purchase#34]
Is the subscription api different or the same?

If different, any documentation or a sample app.

Thank you for your work.

**Comment by PeterStaev** [comment]
Hey @erjdriver , the API is the same. In order to verify your subs you have to send your subscription/transaction details to your backend and then verify that with Apple/Google APIs. you can read more in this comment: https://github.com/PeterStaev/nativescript-purchase/issues/2#issuecomment-356326926

**Comment by erjdriver** [comment]
Ok thanks - will look at that.

Would also appreciate a demo app - or some good docs on the verification process.

I use Nativescript w/ TS.

Thanks.

**Comment by PeterStaev** [comment]
Well I've started on a blog post, but cant find the time to finish it... But the verification is not done by the app/plugin as it is done by your backend. So a demo app is not much possible. Also validation is not specific to NativeScript. So anything you find about validation on google can be applied. For example:
[Validating to the Apple App Store](https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html#//apple_ref/doc/uid/TP40010573-CH104-SW1)
[Apple App Store Status Update Notifications](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html#//apple_ref/doc/uid/TP40008267-CH7-SW13)
[Google Play Store Real-time Developer Notifications](https://developer.android.com/google/play/billing/billing_subscriptions.html#realtime-notifications)

**Comment by erjdriver** [comment]
Ok thanks - I plan to add it soon.
