### ISSUE TITLE
Yet another subscription question (ios)

### ISSUE THREAD

**Issue by erjdriver** [PeterStaev/nativescript-purchase#35]
My understanding is the version 2.0 supports auto-renewable subscriptions (ARS).

Being that the work flow is the same as other IAP - what what does the plugin handle specific for ARS - IOW - what was done.

I've been reading up the docs for ios  ARS - most seem to be server-to-server between Apple and my server - understand  that.

I was just wondering what was added to the plugin to support ARS.

Again some documentation would be of great help.

Thanks.

**Comment by PeterStaev** [comment]
@erjdriver , you can review the changes made in the following 2 commmits: https://github.com/PeterStaev/nativescript-purchase/commit/620c1c98d0f0c014b40116e11b2e344fb300c804 https://github.com/PeterStaev/nativescript-purchase/commit/f770fc1e7343eabc1d2c007c7d3a29f287548bcf

Basically most of the changes were for android to be able to pull both types (`inapp` and `subs`) as before this was hardcoded to `inapp` only. Also each product has now a properties specifying the type of the product (`inapp` or `sub`) as well as the renew period if it is a subscription (considering the notes for iOS here: https://github.com/PeterStaev/nativescript-purchase/issues/2#issuecomment-356326926). Also specifically for iOS a `getStoreReceipt()` method was added which allows you to easily pull the receipt in Base64 format which you can then directly send to your backend for subscription validation (for android the receipt was already part of the transaction). 

Considering that the whole validation process is happening on the server, and does not happen in {N}/this plugin, and considering that there are numerous articles how to do it on different server architectures, I do not think any additional documentation for the plugin is needed. But I'm happily accepting PRs if you think something in the readme can be improved 😃

**Comment by erjdriver** [comment]
I read that the receipt verification doesn't necessarily needs to be done on one's own server.

Of course more secure. But I guess it depends on the app - my app is low volume and I don't think anyone with bother spoofing a receipt. That said, I will most probably implement something on the server - just for future projects.

Does your plugin handle CANCEL events?

**Comment by PeterStaev** [comment]
Not sure what do you mean with cancel events.

**Comment by erjdriver** [comment]
I meant cancellation of Subscriptions.

Doesn't that event appear in the transaction queue, if iTunes cancels a subscription (via user)

https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html#//apple_ref/doc/uid/TP40008267-CH7-SW13

Table-6-4.

I know that's server-to-server - but wouldn't these events also appear in the transaction queue when the app starts up???

**Comment by PeterStaev** [comment]
To be honest I have no idea. I guess you can try it and see if the callback will be triggered 😉

**Comment by erjdriver** [comment]
Sure - I plan to write a separate test app that tests subscriptions (ios) thoroughly and I'll send you a feedback when done.

Thanks again.
