### ISSUE TITLE
Plugin compatible with NS 4.0

### ISSUE THREAD

**Issue by erjdriver** [PeterStaev/nativescript-purchase#36]
I installed plugin version 2.0 and it requires tns core modules 3.0

Can you make it compatible with 4.0

p.s. that's the minimum plugin version compatible with subscriptions right?

**Comment by PeterStaev** [comment]
@erjdriver , this is just an npm warning because of the peer dependencies. You can ignore that for now. The plugin does not use anything specific that was changed in 4.0 so it should be working as expected.
