### ISSUE TITLE
Android takes ~10 seconds to load products

### ISSUE THREAD

**Issue by r0zar** [PeterStaev/nativescript-purchase#37]
Is this know or am I doing something wrong?

Have yet to test on iOS.

**Comment by PeterStaev** [comment]
Hey @r0zar , I guess it depends on device/I-net speed. Sometimes it is a bit slow, but this is the speed of how Google/Apple responds to the requests.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.

**Comment by r0zar** [comment]
Fine with me. I'll post an update if anything relevant come's up.
