### ISSUE TITLE
Problem validating the store receipt (ios)

### ISSUE THREAD

**Issue by erjdriver** [PeterStaev/nativescript-purchase#38]
When I get notified of a transaction (via plugin callback), I send it to my server and then forward the transactionReceipt field (base64) to iTunes and validate it (along with my password) - and that works.

But when I do a getStoreReceipt() and then send that to the same server for validation, I get status=21002 - receipt-data malformed.

I logged the data returned by getStoreReceipt on the client side - when decoded - results in a string with binary characters.

Nothing like the transactionReceipt field of a Transaction object.

The store-receipt - when I decode the base64 - should be ascii right?

**Comment by PeterStaev** [comment]
I do not think the receipt data is in readable format when decoded. But strange why you get the error. Might be because i'm outputing the string with new lines so that all lines are up to 64 characters. Can you try and strip all new line characters (both carriage return and line feed) from the store receipt string before sending it for validation to Apple?

**Comment by erjdriver** [comment]
The transactionReceipt in your Transaction object is base64 and when decoded is ascii. 

Not quite Json - but ascii.

The getStoreReceipt() data doesn't seem to be ascii.

That concerned me a little bit because the same code on the itunes server should be processing both.

Point of failure could be transmission/receive from the app to my server.

But for test purposes - I can send the message directly from my app to itunes - without the CRLFs.


I'll test it and let you know.

**Comment by erjdriver** [comment]
That was the problem.

Setting this line (purchase.ios.js: line #75) from 1 to 0 - fixes the problem

`return receiptData.base64EncodedStringWithOptions(0 /* Encoding64CharacterLineLength */);`
