### ISSUE TITLE
iOS: Unable to load products

### ISSUE THREAD

**Issue by r0zar** [PeterStaev/nativescript-purchase#40]
I can get my products on Android but unable to get them from defined products in iTunes Connect.

The logs show it is connecting but finding 0 products.

Any help would be greatly appreciated.

**Comment by r0zar** [comment]
Does my "Paid Application Contract" need to be put "into effect" (aka I've entered contact, billing and tax info) before I can even test in app purchases?

**Comment by r0zar** [comment]
I think this may be the issue but confirmation would be helpful

**Comment by PeterStaev** [comment]
I can't confirm, since I've enabled this loooong time ago 😃 But I think we had to accept all contracts/license terms before even be able to add a purchase.

**Comment by r0zar** [comment]
I'll close and revisit after bank account is linked.
