### ISSUE TITLE
Products wont load?

### ISSUE THREAD

**Issue by r0zar** [PeterStaev/nativescript-purchase#42]
Is there any reason this plugin might perform differently in an Angular app?

I'm unable to get my iTunes Connect products to load at all, and for android (as some have noted) it is quite slow.

I was able to load and run the vanilla ts demo app provided with the repo, and able see products listed.

Any insight is appreciated. Banging my head on this one trying to make sense of why I can't load products on iOS.

**Comment by r0zar** [comment]
I'm going to create a fresh app and see if I'm able to load purchases into it. Will share the repo as soon as its ready. Hopefully it just works.

**Comment by PeterStaev** [comment]
The code does not use any core/angular things, so it should not make any difference. Feel free to trace and in case you find the cause I'm happily accepting PRs 😉

**Comment by r0zar** [comment]
Thanks, will have an update in a few hours.

**Comment by r0zar** [comment]
Okay, so i hacked my project to point at `com.tangrainc.purchasesample`, and used the purchase items you have in the demo, and was able to load them. so my code is fine, the problem is with my items in iTunes connect it seems. I've followed the tutorial exactly but the response from `purchase.getProducts().then((products: Array<Product>) => {` is always nothing...

**Comment by r0zar** [comment]
IT WORKS! 🎉 Although my subscriptions are coming in without a title... hmm on to the next problem!

Thanks for responding to my complaints, it helped! haha.

**Comment by PeterStaev** [comment]
Glad you had it sorted!
