### ISSUE TITLE
Wrong product prices

### ISSUE THREAD

**Issue by BearOutThere** [PeterStaev/nativescript-purchase#47]
One of the products is priced at 3500.00 but the number that comes back from the plugin is -794.967296 as shown below.  This is clearly wrong.  I found a report of a similar problem at this link and the proposed solution is to use a long instead of an int.
https://answers.unrealengine.com/questions/604873/in-app-products-wrong-price.html

This is the debug data from plugin's purchase.getProducts() method.
`:Product
__proto__:ProductBase
localizedDescription:"฿ 350 / credit"
localizedTitle:"10 Credits (90 Day Reporter)"
nativeValue:Object
priceAmount:-794.967296
priceCurrencyCode:"THB"
priceFormatted:"THB 3,500.00"
productIdentifier:"11"
productType:"inapp"
`

It also appears that changes to the product prices are not being shown in the app even 2 days after the changes were made.  Not sure if it's the plugin or the store problem.

**Comment by PeterStaev** [comment]
Hey @bearoutthere , thanks for the link! I've just published a new version on npm that uses `getLong`. Please try it out and see if that fixes the number problems. 

As for the product prices not showing - from what I see the plugin does not cache anything so I guess this is what the android services return. Make sure the new prices are applied in Google Dev Console and try rebooting your phone to possibly clear the billing service cache.

**Comment by BearOutThere** [comment]
Thanks Peter.
That solved the problem.
