### ISSUE TITLE
"Product already purchased" error comes up before purchase.transactionUpdatedEvent is called

### ISSUE THREAD

**Issue by BearOutThere** [PeterStaev/nativescript-purchase#48]
Got a strange problem. 
I was doing some refactoring that generated some errors before consumption call could be made.
After i fixed those errors now i'm getting "Product already purchased" error immediately on 

`
    helper.startBuyIntent(application.android.foregroundActivity, product.productIdentifier, product.productType, developerPayload || "");

`
in purchase.android.js line 94.   The purchase.on(purchase.transactionUpdatedEvent... event handler is not being called at all, which is where my consumption call is.  But it never gets there. Google Pay dialog does not appear.  I tried uninstalling app from the emulator, clearing app cache and data, clearing Genymotion emulator cache. Nothing works.

The strangest thing is that this problem only happens for 2 products.  The third product works fine.  Google Pay dialog comes up, i can purchase it, the handler event gets called and, in turn, calls the consume function.  

So it feels like previous errors somehow screwed things up for these 2 product.  I've tried many things and pretty stumped right now.  Any ideas would be greatly appreciated.

**Comment by PeterStaev** [comment]
Hey @bearoutthere , if you purchased those products BEFORE you added the consumption logic then those are locked and you cannot start again a buy workflow for those products unless you consume your previous purchases. So I would suggest you trigger the restore purchase workflow and then consume all purchases that you receive. Once those are cleared from your account, you should be able to use your normal workflow.

**Comment by BearOutThere** [comment]
That's what i thought.  Will give it a try tomorrow.  Thanks Peter.

**Comment by BearOutThere** [comment]
So i finally tried your suggestion above and when i try to consume restored transactions consumePurchase() returns responseCode of 5 not 0.  And the products are still locked and cannot be purchased.  I looked in the documentation but can't find what code 5 means.  Help.

**Comment by PeterStaev** [comment]
You don't consume a restored transaction. You need to call consume on the `originalTransaction` that is part of the transaction. If that doesn't work, then I guess no way to consume those purchases and you have to use another account/add another products.

**Comment by BearOutThere** [comment]
That worked.   Thanks.
