### ISSUE TITLE
Add to documentation a note about contracts

### ISSUE THREAD

**Issue by geoffbullen** [PeterStaev/nativescript-purchase#50]
Hi, thanks for the plugin!

I wasted a lot of time until I learned that you require a paid contract in effect in order for getProducts() to return anything.   Maybe a note in the doco could save someone else from this pain :-)

<img width="963" alt="contract" src="https://user-images.githubusercontent.com/2024640/43234301-aa77e438-90be-11e8-82c5-86f457fffa75.png">

**Comment by PeterStaev** [comment]
Thanks! Will see to add this in the step by step guides.

**Comment by milejko** [comment]
@geoffbullen is it specific to iOS, Android or both?

**Comment by geoffbullen** [comment]
> @geoffbullen is it specific to iOS, Android or both?

iOS

**Comment by PeterStaev** [comment]
Done.
