### ISSUE TITLE
Transaction.nativeValue is empty

### ISSUE THREAD

**Issue by rohanrichards** [PeterStaev/nativescript-purchase#52]
I'm trying to implement back end validation for purchases using an npm module that requires an object (JSON or JS) that represents the receipt, looking through issues/docs on that modules page suggests the object should look something like this:

```
"data":{
"packageName":"com.fanhero.floridacup",
"productId":"com.fanhero.subscription.monthly",
"purchaseTime":1486056847995,
"purchaseState":0,
"developerPayload":"474E6yrV6JDFWBobm7DrBu",
"orderId":"GPA.1331-4662-9366-45997",
"purchaseToken":"gjbemoolbkmdedknfodeibai.AO-J1OwpS4EPqxR72fPO2zfBe1IB4ZmCNZVNQwkBoGFmq3qLeT7JTyo_qHOlEYc1d-XYDZ74AT0gNqfKBHLqzU_JT3s5879W66ARA7EPF8W7c_SbwAfzT-GKICRMZHpjnc1JlICrj-aSYx0VeHU_0L813i3Q0LM32Q",
"autoRenewing":true
}
```
* I've pulled the above sample data from here : https://github.com/voltrue2/in-app-purchase/issues/79

I believed Transaction.nativeValue would be the correct way to get this data, however whenever I return it from my test device it is an empty object `{}`

I have also tried returning the entire Transaction object to my back-end but the result is the same.

I am currently testing on android.

Just a question, however if I returned the raw Transaction.transactionReceipt string, could I decode it myself using the Transaction.signature to get the original receipt object?

**Comment by PeterStaev** [comment]
Hey @rohanrichards , the `nativeValue` property is an `org.json.JSONObject` instance. So I think you will need to stringify that before sending it to the plugin. Another way would be for yourself to create the above JSON object by using the properties of the `Transaction` object itself. You can see the mapping that is done here:
https://github.com/PeterStaev/nativescript-purchase/blob/bc02f758f9da6e83dfa89cab52c47a1e7418f435/transaction/transaction.android.ts#L23-L56

**Comment by rohanrichards** [comment]
## EDIT 2
I feel a bit stupid, all I needed to do was call the Java Object's `.toString()` method instead of JavaScripts `JSON.stringify()` method.

Here's my implementation (with extraneous try/catch block) that also, *I hope*, handles iOS purchases:
```
		let payload = {};
		let native = {};
		try {
			native = transaction.nativeValue.toString();

		}catch {
			native = JSON.stringify(transaction.nativeValue);
		}

		if(transaction.dataSignature){
			payload = {
				data: native,
				signature: transaction.dataSignature
			};
		}else {
			payload = transaction.transactionReceipt;
		}
```

## EDIT
`JSON.stringify(transaction.nativeValue)` still returns an empty object. Here's my code: 

Component (inside ngOnInit)
```
		purchase.on(purchase.transactionUpdatedEvent, (transaction: Transaction) => {
			if (transaction.transactionState === TransactionState.Purchased) {
				this.handlePurchase(transaction)
			}
...
		});
```
(inside handlePurchase)
```
    this.purchaseService.validatePurchase(transaction).subscribe(res => {
```

Service (validatePurchase)
```
	validatePurchase(transaction) {
		let payload = {};
		if(transaction.dataSignature){
			payload = {data: JSON.stringify(transaction.nativeValue) , signature: transaction.dataSignature};
		}else {
			payload = transaction.transactionReceipt;
		}
		console.log('service about to validate with transaction: ', payload);

		return this.AuthHttp.post(`http://192.168.1.100:3000/api/purchases/validate`, payload)
			.map((res: Response) => res.json())
	}
```

I'm sure this is a bug, but I'll try manually building a receipt object as per the mappings you've provided just to keep up development until someone can advise me on how to get around this.

## Original Message
@PeterStaev Thank you for this, I think my mistake was not realising or noticing the distinction between a `org.json.JSONObject` **instance** and just a plain JSON object string.
I will play around with stringifying tomorrow at work and will get back to you, I dare say this is the solution though.
Thank you for the snippet too for the mapping, I can at least manually create it if all else fails!

Just for clarification, will `JSON.stringify(transaction.nativeValue)` do the trick? Or do I need to handle this differently because its a Java object (is that right? it's org.json which is a Java lib?)
