### ISSUE TITLE
Consuming old purchases

### ISSUE THREAD

**Issue by rohanrichards** [PeterStaev/nativescript-purchase#53]
I have found myself in an odd position in Android where I've had a purchase but did not consume it. This is because I was waiting for server side validation before consuming, and in my case the validation failed.
My Product is now in a state where it is purchased, but not consumed, so now the test user cannot purchase it again.
I have tried `purchase.restorePurchases()` and that may have worked once, however due to a bug in my handleRestore method the consume method never fired. restorePurchases now returns nothing as I think they have technically been "restored" yet are still not consumed.
How can I get my hands on previous purchases to consume them? What's the best practice here for this situation (a consumable purchase fails to consume)?

**Comment by PeterStaev** [comment]
Hey @rohanrichards , I think `restorePurchases` should always return the purchases if they are not consumed. This is the only way I know you can get previous purchases. If it does not work, then you are out of luck and should add another purchase or use another account for testing.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
