### ISSUE TITLE
Subscription in Android environment.

### ISSUE THREAD

**Issue by nelsongsa** [PeterStaev/nativescript-purchase#54]
Hi i want only ask if the function to get subscriptions from google play is not available yet in the plugin, thank you.
all the best.

**Comment by PeterStaev** [comment]
I’m not aure what do you mean. The plugin does support subs.

**Comment by nelsongsa** [comment]
Yes, in the Documentation say that the plugin Doesn't support the subscriptions on Android.

https://www.tangrainc.com/blog/2017/06/implementing-app-purchases-nativescript-application-part-3/

in this link the documentation says:

"Remember that for now the nativescript-purchase plugin does not support subscriptions so make sure you select the Managed Product option"

**Comment by PeterStaev** [comment]
That was at the time of the writting of that blogpost. As of version 2.0 and as per the readme the plugin does support subs.
