### ISSUE TITLE
Always receiving transaction code failed

### ISSUE THREAD

**Issue by empoplawski** [PeterStaev/nativescript-purchase#55]
Hello, I am using this with a nativescript angular implementation.. I have the products configured and connected through apple connect, but whenever I go to confirm my purchase, I receive a transaction status of failed. I saw in a similar issue that this plugin does not support subscription purchases. In this instance the purchases I am making are consumable goods. 

my code on this page instantiating the purchase are as follows

```  onProductTap(item) {
    console.log("tapped it")
    let product = item
    console.log("this is the item", product)

    purchase.buyProduct(product);
  }

purchase.on(purchase.transactionUpdatedEvent, (transaction: Transaction) => {
  console.log("transaction", transaction)
  console.log(transaction.transactionState)
  if (transaction.transactionState === TransactionState.Purchased) {
    console.log("transaction in purchased", transaction)

    alert(`Congratulations you just bought ${transaction.productIdentifier}!`);
    console.log(transaction.transactionDate);
    console.log(transaction.transactionIdentifier);
    applicationSettings.setBoolean(transaction.productIdentifier, true);
  }
  else if (transaction.transactionState === TransactionState.Restored) {
    console.log(transaction.transactionState)
    console.log(`Purchase of ${transaction.productIdentifier} restored.`);
    console.log(transaction.transactionDate);
    console.log(transaction.transactionIdentifier);
    console.log(transaction.originalTransaction.transactionDate);
    applicationSettings.setBoolean(transaction.productIdentifier, true);
  }
  else if (transaction.transactionState === TransactionState.Failed) {
    console.log("failed")
    console.log("transaction in failed", transaction)
    console.log(transaction.transactionState)
    alert(`Purchase of ${transaction.productIdentifier} failed!`);
  }
});

``` 

I have tried logging as much information as possible and cannot find any useful clues. I have also tried testing on emulators and physical devices both through my own environment and xcode.

**Comment by PeterStaev** [comment]
Hey @empoplawski , please see to follow the the step by step guide on how to integrate in-app purchases for iOS. Everything explained is important there, so be sure not miss anything 😉 Also last time I checked buying products does **not** work in iOS simulators, so you need to use an actual device.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
