### ISSUE TITLE
Trying to upgrade to latest 2.0.5

### ISSUE THREAD

**Issue by erjdriver** [PeterStaev/nativescript-purchase#56]
I'm using NS 5.0.3, tns-core-modules 5.0.5 and tns-ios 5.0.0

Using nativescript-purchase 2.0.1.

I see the latest is 2.0.5 but when I do npm outdated - I do not get a list that says the nativescript-purchase can be upgraded.

How do I upgraded to 2.0.5?

Also, is there a way to find out what changed in each version update.

Thanks.

**Comment by PeterStaev** [comment]
Hey @erjdriver , the version published on npm is 2.0.5. So you probably already have that if `npm update` does not show anything. You can check in your `.lock` file what is the version of the package. If everything fails you can always remove and reinstall it, which will for sure install the most recent version 😉 

I publish release notes for major/minor versions under releases in GH. For revision versions, they only contain small fixes, so you can track those via the separate commits on GH.
