### ISSUE TITLE
Android Error: java.lang.Exception: Failed resolving method addCallback on class com.google.common.util.concurrent.Futures

### ISSUE THREAD

**Issue by marcelomiranda90** [PeterStaev/nativescript-purchase#59]
Hi, I'm getting this error while trying to make the purchase.

Before everything was working well and I made sales without any problems, but after some updates I started getting this error.

```
JS: ERROR Error: Uncaught (in promise): Error: java.lang.Exception: Failed resolving method addCallback on class com.google.common.util.concurrent.Futures
JS:     com.tns.Runtime.resolveMethodOverload(Runtime.java:1079)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:987)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:967)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:959)
JS:     com.tns.gen.com.google.android.gms.tasks.OnCompleteListener.onComplete(OnCompleteListener.java:16)
JS:     com.google.android.gms.tasks.zzj.run(Unknown Source)
JS:     android.os.Handler.handleCallback(Handler.java:754)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:163)
JS:     android.app.ActivityThread.main(ActivityThread.java:6238)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCa...
```

I researched a lot and it seems to be something with the guava version, but I could not solve it.

If you can help me, I'll be very grateful.

Anyway, congratulations on your great work.

**Comment by marcelomiranda90** [comment]
I changed the futureToPromise function to the code below and it worked again.

I do not know if it's something general, or it's some plugin I'm using that is using another version of guava and generating the problem.

If you can review and if necessary update your code.

```
function futureToPromise(future /* ListenableFuture */) {
    return new Promise(function (resolve, reject) {
        com.google.common.util.concurrent.Futures.addCallback(future, new com.google.common.util.concurrent.FutureCallback({
            onSuccess: function (result) {
                resolve(result);
            },
            onFailure: function (t /* Throwable */) {
                reject(new Error(t.getMessage()));
            }
        }),
        com.google.common.util.concurrent.MoreExecutors.directExecutor());
    });
}
```

**Comment by PeterStaev** [comment]
Hey @marcelomiranda90 , first of all thanks for reporting this as well as providing what resolved the issue! This is a really strange problem and seems like {N} cannot resolve the methods that has only 2 arguments, but successfully resolves the method with the 3 arguments, although from what I see both methods were present since guava v10. 
Can you tell me what version of Nativescript runtime are you using as well as the version of the core modules? I want to try and simulate this and possibly submit a bug report to Nativescript Android runtime.

**Comment by marcelomiranda90** [comment]
Thanks for the quick response.

Below is package.json with all the plugins used, I suspect it might have something to do with the firebase plugin, because it was after an update that I had the problem.

As for tns-core-modules, I tried version 5.0.5, but it also did not work.

What I have the impression is that for some reason, some newer version of guava has been used in the compilation.

I am available for any other information that may help us resolve the problem.

Thank you very much.

```
    "tns-android": {
      "version": "5.1.0"
    }
  },
  "dependencies": {
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/http": "~7.1.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "nativescript-angular": "^7.1.0",
    "nativescript-cfalert-dialog": "^1.0.13",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-modal-datetimepicker": "^1.1.12",
    "nativescript-numeric-keyboard": "^4.2.0",
    "nativescript-plugin-firebase": "^7.6.0",
    "nativescript-purchase": "^2.0.5",
    "nativescript-ratings": "^1.0.1",
    "nativescript-snackbar": "^4.0.0",
    "nativescript-social-share": "^1.5.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-chart": "^3.11.1",
    "nativescript-ui-dataform": "3.7.2",
    "nativescript-ui-listview": "^5.0.1",
    "nativescript-ui-sidedrawer": "^5.1.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^6.3.3",
    "tns-core-modules": "5.0.5",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~7.1.0",
    "@nativescript/schematics": "~0.4.0",
    "@ngtools/webpack": "~7.1.0",
    "nativescript-dev-typescript": "^0.7.8",
    "nativescript-dev-webpack": "^0.18.5",
    "tns-platform-declarations": "^5.1.1",
    "typescript": "~3.1.1"
  }
```

**Comment by PeterStaev** [comment]
Hey @marcelomiranda90 , I had the time to play with the problem in a sample app, but I was not able to reproduce it (tried couple of newer/older versions of Guava). But after reading the docs seems that when you don't pass an executor by default it uses the `directExecutor`. So I've changed the code to the one you suggested above and the new version is now on NPM. Hopefully this will resolve the problem.

**Comment by ghost** [comment]
Hello, just a comment.
I began to work with this plugin 3 months ago approximately, (Jan 2019) at the beginning all worked fine, but as Marcelo says, after some upgrades including NS, tns-core-modules etc, and installing other plugins, this plugin started getting this error when I called purchase.getProducts()..., but as I was working on other features of my app I'm unable to say with which exact upgrade it started to fail, but I can say I had installed the 2.0.5 version. Today I upgrade the plugin to the last version (2.0.9) and it works fine again, so the upgrade was great and effective. So my comment is just to mention the versions and other plugins that could have lead to this error, I'm working with these ones:
tns-android 5.3.1
angular/core: ~7.1.0
nativescript-angular: ~7.1.0
tns-core-modules: ^5.3.1
typescript: 3.1.1
zone.js: ~0.8.18
angular/cli: 7.2.3
angular/compiler-cli: ^7.2.7
and Android API 28.
The plugins I installed after nativescript-purchase are:
nativescript-ui-sidedrawer: ^6.0.0
nativescript-imagepicker: ^6.1.2
nativescript-checkbox: ^3.0.3
nativescript-camera: ^4.3.0
and nativescript-plugin-firebase: ^7.7.0, (maybe it was firebase, after all).
I know this info is vague but it could give some glimpse of what could been happen.
And thank you for made this plugin, it's great!
