### ISSUE TITLE
Add SKPaymentTransaction.error field to Transaction

### ISSUE THREAD

**Issue by bytesoverflow** [PeterStaev/nativescript-purchase#6]
My payments are failing and I don't have access to the underlying SKPaymentTransaction.error field. It should be trivial to add it in transaction/transaction.ios.ts, would you like me to make a pull request?

**Comment by PeterStaev** [comment]
Hey @tobydeh , the underlying native transaction object is accessible via the `nativeValue` property: https://github.com/PeterStaev/nativescript-purchase/blob/master/transaction/transaction-common.ts#L20

**Comment by bytesoverflow** [comment]
My bad, thank you.
