### ISSUE TITLE
Upgrading from 1.x to 2.0.9

### ISSUE THREAD

**Issue by erjdriver** [PeterStaev/nativescript-purchase#74]
I upgraded from 1.x to 2.0.9.

When I click on a product to purchase - I get a "purchasing" callback - but the transactionDate and transactionReceipt fields are undefined.

And then I get the "failed" callback - with the same parameters.

Is there a documentation on the diferences between 1.x and 2.x - any samples.

I know developer-payload feature has been added.

Thanks.

**Comment by PeterStaev** [comment]
Hey @erjdriver , what platform is this? Main addition is the subscription. But there have been couple of fixes when sometimes the native transaction value ends up as null so it could happen sometimes now that the whole transaction is undefined.

**Comment by erjdriver** [comment]
Apologies - its ios and am using the latest NS.

This should work on the ios simulator right or need device?

Does the sample go over the developer-payload feature?


Also, the "failed" message doesn't contain any reason for the failure.

**Comment by PeterStaev** [comment]
@erjdriver , purchases do **not** work in the simulator. You need an actual device. Please refer to the [in depth tutorial for iOS](https://www.tangrainc.com/blog/2017/03/implementing-app-purchases-nativescript-application-part-2/). 

As for the `developerPayload` it is not added to the demo, but it is nothing much - just send some string when you call `buyProduct` and you should get it in the corresponding transaction for the product once it is purchased.

**Comment by erjdriver** [comment]
OK - apologies again.

I will try the developerPayload field.

I see there's coupla new fields "productType" and "subscriptionPeriod". Are these just informational info?

Is there any callback or flag that tells me that the user cancelled the subscription?

Thanks.

**Comment by PeterStaev** [comment]
The `productType` is meant for you distinguish between in-app and sub based products and is iniformational. 
The `subscriptionPeriod` is again informational and is meant to show you at what interval the sub will renew. 

There is no callback/flag to notify you in-app for a sub cancellation. you have to have a backend server that will use the provided for each platform services that allows you to pull the state for subscriptions.
