### ISSUE TITLE
class Transaction missing public error: any;

### ISSUE THREAD

**Issue by Ianc22** [PeterStaev/nativescript-purchase#75]
Hi Peter,

We have to update transactions,d,ts and include the error prop as the build fails otherwise stating that transaction.error does not exist. Can you please fix it when you get a minute?

Thanks in advance,

Ian

**Comment by PeterStaev** [comment]
Hey @Ianc22 , the `Transaction` object does not have any `error` property.

**Comment by Ianc22** [comment]
Hey Peter, right thanks for the heads up! My colleague implemented the code, just looked at it. checking error on the transaction. I'll remove that bit of code then. Sorry for the false alarm!
