### ISSUE TITLE
purchase.getProducts throws error with Response code 5 on Android when initialized with more than 20 products

### ISSUE THREAD

**Issue by ajaymaru** [PeterStaev/nativescript-purchase#78]
When the plugin is initialized (purchase.init) with more than 20 products, subsequent call to purchase.getProducts throws error: "Error: Response from service: 5"

If there are 20 or fewer products, then the plugin works as expected and quite nicely.

Not sure if I am missing something. Any pointers will be greatly appreciated.

**Comment by PeterStaev** [comment]
Hey @ajaymaru , seems on android you cannot pull all the products (in case there are more than 20), but instead you need to pull them in chunks: https://stackoverflow.com/a/21080893/5272836.

Currently the plugin does not do this, so that's why you get that error.

**Comment by ajaymaru** [comment]
Thanks @PeterStaev for quick response.

**Comment by ajaymaru** [comment]
@PeterStaev, I have looked through the code and working on the enhancement. Will send you a pull request once I have it tested at my end.

**Comment by ajaymaru** [comment]
@PeterStaev, sent the PR (#79 ) for your review when you get a chance. Thanks.

**Comment by PeterStaev** [comment]
Thank you! New version on npm (2.0.13) includes your fix.
