### ISSUE TITLE
Check if product was already purchased

### ISSUE THREAD

**Issue by jayhaluska** [PeterStaev/nativescript-purchase#80]
What is the standard way to check whether an item was already purchased?
I'm not talking about consumable products.

At the moment I'm saving a variable in the application settings to save the purchased status of my product. But when I uninstall my app and reinstall, the purchased status is lost.

At first I thought, I'll do it with `restorePurchases()`, but the `transactionUpdatedEvent` is not triggered. Any idea why?

The only way left is to catch the Exception like in #45. If that is the standard way, then I would suggest adding this to the readme.

**Comment by PeterStaev** [comment]
Hey @jayhaluska , what you are doing is the correct way to do it. Save the purchased item locally. Then if the user installs the app on another device (or reinstalls is) they must trigger restore purchases and this will trigger the transaction updated event. Not sure why it is not called in your case, but last time I tried it it was called just fine.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
