### ISSUE TITLE
Is this plugin compatible with {N} version 6?

### ISSUE THREAD

**Issue by douira** [PeterStaev/nativescript-purchase#86]
The Nativescript marketplace says there support for version 6. https://market.nativescript.org/plugins/nativescript-purchase
If it is not supported, the marketplace should probably reflect that.
Also, is there another plugin for in-app purchases? This kinda seems like an essential component of the framework and it's weird there isn't any support from Nativescript itself. (like there is also core support for dialogs, app settings, file system, networking etc.)

**Comment by PeterStaev** [comment]
Hey @douira , the public version of the plugin _should_ be compatible with NS 6 since it does not reference anything about `androidx` which messed up most plugins, but hasn't been tested.

**Comment by wpatter6** [comment]
This seems to possibly be crashing my NS 6 app.  I can't run the `tns plugin add @proplugins/nativescript-purchase` command, it gives an error `404 Not Found: @proplugins/nativescript-purchase@latest`

@PeterStaev please advise on how this plugin's latest version can be used

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
