### ISSUE TITLE
"Error decoding object" on getProducts() call on iOS 13

### ISSUE THREAD

**Issue by yoat** [PeterStaev/nativescript-purchase#87]
My code works on Android and iOS 12, but on iOS 13 there is an exception being thrown in the nativescript-purchase getProducts() call.

```
import * as purchase from "nativescript-purchase";
// ... later on we call getProducts:
 purchase
        .getProducts()
        .then(res => {
          this.products = res;
          console.log(`found ${res.length} products`);
          resolve(this.products);
        })
        .catch(e => {
          console.log(`error getting products: ${e}`);
          reject(e);
        });
```

The output from within the catch block above is:
"error getting products: Error: Error decoding object"

Is there something we have to do differently for iOS 13?

**Comment by yoat** [comment]
Can you confirm the latest version of “PeterStaev/nativescript-purchase” and/or “@proplugins/nativescript-purchase” has been tested to work with iOS 13?

**Comment by PeterStaev** [comment]
Hey @yoat , looking at [this](https://stackoverflow.com/questions/58020258/requesting-an-in-app-purchase-in-ios-13-fails) seems this is a known problem with the new XCode/iOS Sim. Can you try your code on an actual device or reboot the sim/xcode/mac?

From what I know there haven't been any changes to the native APIs in iOS13 and since the plugin directly uses those APIs it should be working just fine. But I haven't tested it personally.

**Comment by yoat** [comment]
I'm running it on actual hardware. The iOS simulators do not support IAPs.

The error I posted is from a debug session on a iOS 13 device.  The same code that works on iOS 12 hardware doesn't work on iOS 13 hardware.

**Comment by PeterStaev** [comment]
[Another post](https://stackoverflow.com/questions/58234217/in-app-purchase-product-retrieval-randomly-fails-with-error-code-507) also suggests some problems with dependencies. Are you using any other plugins in your project that might be using some cocoa pods that might be outdated? Can you try to simulate the problem on a blank project with just the purchase plugin?

And for your reference, specifically the `getProducts()` function works perfectly fine in Simulators 😉 The purchase workflow that initiates an actual purchase is what doesn't work.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
