### ISSUE TITLE
Unsubscribing from auto-renewable subscription

### ISSUE THREAD

**Issue by dhoffens** [PeterStaev/nativescript-purchase#89]
I understand that it is recommended we use server-to-server to validate subs, but how do we actually unsubscribe?

**Comment by PeterStaev** [comment]
Hey @dhoffens , users can unsubscribe by using the provided UI from the native OS. 
For Apple: https://support.apple.com/en-us/HT202039
For Google: https://support.google.com/googleplay/answer/7018481?co=GENIE.Platform%3DAndroid&hl=en

**Comment by dhoffens** [comment]
thanks @PeterStaev !

while I have you, for testing purposes, since the subscriptions would be in sandbox environment and not in settings quite yet, would there be a way to test that whole workflow? (sub and unsub)

Appreciate your prompt response!

**Comment by PeterStaev** [comment]
@dhoffens , I havent implemented subscriptions myself, so can't say for sure how those work in Sandbox. But google yields the following:
https://davidbarnard.com/post/164337147440/testing-auto-renewable-subscriptions-on-ios

Sadly for Android couldnt find anything related so not sure how those work.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
