### ISSUE TITLE
purchase.getProducts() is empty

### ISSUE THREAD

**Issue by sl1der** [PeterStaev/nativescript-purchase#9]
I have installed the plugin and successfully run products.init() in my app.component.ts
But when I call getProducts is returns empty array.

```javascript
  ngOnInit() {
    console.log("Purchases: ", JSON.stringify(purchase));
    purchase.getProducts().then((products: Array<Product>) => {
        console.log("I'm in: ", JSON.stringify(products));
        products.forEach((product: Product) => {
            // does not get here
        });
    });
...
}
```

**Comment by PeterStaev** [comment]
Hey @sl1der , have you added your products to the Google Play/iTunes Connect consoles. Also note the plugin currently only supports in-app purchases, so if you have added subscriptions, those will not be listed.

**Comment by sl1der** [comment]
Hey @PeterStaev,
In the init I passed in
```
"offandpacing_10k_coins"
```
And have added this product name to the app in the iTunes connect console. It is a consumable product. I am not sure how to check if the app is the checking iTunes Connect. In the package.json the id matches the app on iTunes.

Is that all that's necessary for the app to get the products?

**Comment by PeterStaev** [comment]
Have you followed the instructions for sandbox testing your purchases like explained [here](https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnectInAppPurchase_Guide/Chapters/TestingInAppPurchases.html#//apple_ref/doc/uid/TP40013727-CH4-SW4)? Also keep in mind that you need to sign your app with a certificate that enables in-app purchases.

**Comment by Roar1827** [comment]
I think this can be due to an incomplete "Paid Application" contract in iTunes Connect:

<img width="683" alt="screen shot 2017-05-02 at 8 55 05 pm" src="https://cloud.githubusercontent.com/assets/4673180/25645177/a6324e6a-2f79-11e7-857e-d883782b51b8.png">

http://stackoverflow.com/questions/14957328/is-an-active-paid-applications-contract-required-for-testing-in-app-purchase
