### ISSUE TITLE
com.apple.mobile.house_arrest Sidekick

### ISSUE THREAD

**Issue by alexisconsuegra** [PeterStaev/nativescript-purchase#91]

**Comment by alexisconsuegra** [comment]
Hi,
I am using Sidekick to develop an app. I have deployed to two test iPhones. Both are added to the provisioning profile. The app works fine on one of the devices. On the second device the app throws error while starting. Sidekicks reports "unable to start com.apple.mobile.house_arrest.
Any help is appreciated 
Thanks

**Comment by PeterStaev** [comment]
Google is your friend and points to [this](https://github.com/NativeScript/nativescript-cli/issues/4741)
