### ISSUE TITLE
restorePurchases() returns before store receipt is available

### ISSUE THREAD

**Issue by tkrevh** [PeterStaev/nativescript-purchase#92]
While trying to restore the store receipt after a fresh app install, we call restorePurchases()
This however returns immediately, and if we call getStoreReceipt() immediately after, it comes back as null.

As a temporary solution we put the call to getStoreReceipt() into a 5sec setTimeout function, but it would be nice, if this could be implemented as a promise (that doesn't resolve immediately). After some researching, it seems this could be a solution: https://stackoverflow.com/questions/47276769/calling-skpaymentqueue-restorecompletedtransactions-no-response

**Comment by PeterStaev** [comment]
This is now available in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.
