### ISSUE TITLE
tns plugin remove no such file or directory

### ISSUE THREAD

**Issue by alexisconsuegra** [PeterStaev/nativescript-purchase#93]

**Comment by alexisconsuegra** [comment]
Hi,
I am trying to remove the native script nativescript-ui-listview plugin in order to reinstall it. Both update and remove throw error: ENOENT: no such file or directory, open 'C:\...\platforms\ios\myApp.xcodeproj\project.pbxproj'
tns plugin remove nativescript-ui-listview
PS: The reason for the update is that the plugin is not working. Error: NativeScript caught signal 11.

**Comment by PeterStaev** [comment]
Hey @alexisconsuegra , I think you posted this on the wrong repo. You are trying to remove the `nativescript-ui-listview` and this this the `nativescript-purchase`?

**Comment by alexisconsuegra** [comment]
Oops. Sorry. On a separate note. Any chance your plug in could work without turning off the auto signing flag?
Thanks

**Comment by PeterStaev** [comment]
I haven't tried it personally but it should work as long as the auto-signing picks up the provisioning that has in-app purchases configured.

**Comment by alexisconsuegra** [comment]
Ok Let me check if the provisioning profile has the in-app purchases and try
Thanks

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
