### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by erjdriver** [PeterStaev/nativescript-purchase#96]
Apologies to using this to get in touch with you - didn't see no other means.

I'm using v 1.0.5 - will this work with NS 6.5 - at least the functionality that's in there.

I know this plugin has gone to pro-plugins - but at this time I'd rather not join up.

I already donated to your cause years ago - 

if i can get access to the latest version - happy to do again.

Pls advise.

**Comment by PeterStaev** [comment]
Hey @erjdriver , sadly I cant guarantee that the version will work. I don't think any of the breaking changes in the past NS versions have influenced this specific plugin. So your best try it to try it and see.
