### ISSUE TITLE
Products list is empty

### ISSUE THREAD

**Issue by vahidvdn** [PeterStaev/nativescript-purchase#98]
Hi. I have the following implementation. But the products list is empty. (I've submitted my app as a beta release at Google Play and added a product id)

main.ts
```TS
...
platformNativeScriptDynamic().bootstrapModule(AppModule);
purchase.init(['prod_purchase']);
```

items.componet.ts
```TS
purchase.getProducts().then((products: Array<Product>) => {
    // result: []
    alert("Products: "+ JSON.stringify(products));
}
```

Any idea?

**Comment by PeterStaev** [comment]
Hey @vahidvdn , from what I see from your code you are not waiting for the plugin to be initialized. Per the [Usage](https://github.com/PeterStaev/nativescript-purchase#usage) it is recommended (if not required) you surround your getProducts with the wait for the init promise. Also for NG, I'm not sure if in the `main.ts` isn't a bit early in the lifecycle. You can as well try to call init in your AppComponent instead.

**Comment by vahidvdn** [comment]
@PeterStaev I use `getProducts` in a button click event. But I will try what you mentioned to see if it's working or not. Thanks.

**Comment by vahidvdn** [comment]
@PeterStaev I tested it but still the same problem. (I'm not sure that I can run the project from the cli or I should submit a new version in Google Play. Can I just run the app or I should build a production version and submit it in Google Play?)

**Comment by vahidvdn** [comment]
There was a problem with Google Play console. It's working now. Thanks.
